apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fnsv4tg0s-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fnsv4tg0s-java-springboot-gitops